### ISSUE TITLE
Version 4.1.6 crashes on launch

### ISSUE THREAD

**Issue by ramesh45345** [flathub/com.belmoussaoui.Authenticator#15]
The latest version of Authenticator on flathub (`4.1.6`) crashes on load. The following logs were produced (I'm actually not sure how helpful they are.

```
$ flatpak info com.belmoussaoui.Authenticator                                                                                                                                                                                        Thu 01 Sep 2022 07:02:37 PM EDT

Authenticator - Generate Two-Factor Codes

          ID: com.belmoussaoui.Authenticator
         Ref: app/com.belmoussaoui.Authenticator/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.1.6
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 50.3 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: b3c03b7daf765e06dfabd23a0a1fe3f64f69560f0bfb299e808950c529de96a7
      Parent: 580ae717f62d9eac3a4d2bdd6c0dfbf0f4fe22f962af20a05b65bd888019797b
     Subject: Release 4.1.6 (d4ea4bdb)
        Date: 2022-06-10 19:58:57 +0000
$ env RUST_BACKTRACE=full flatpak run com.belmoussaoui.Authenticator                                                                                                                                                                 Thu 01 Sep 2022 07:02:57 PM EDT
2022-09-01T23:03:16.849171Z  INFO authenticator::application: Authenticator (com.belmoussaoui.Authenticator)
2022-09-01T23:03:16.849205Z  INFO authenticator::application: Version: 4.1.6 ()
2022-09-01T23:03:16.849208Z  INFO authenticator::application: Datadir: /app/share/authenticator
thread 'main' panicked at 'Failed to start a location service: Portal(CancelledPortalRequest)', src/application.rs:326:18
stack backtrace:
   0:     0x55a23b659d7d - <unknown>
   1:     0x55a23b67c7ec - <unknown>
   2:     0x55a23b653ac1 - <unknown>
   3:     0x55a23b65b8a5 - <unknown>
   4:     0x55a23b65b559 - <unknown>
   5:     0x55a23b65bdf2 - <unknown>
   6:     0x55a23b65bcd7 - <unknown>
   7:     0x55a23b65a234 - <unknown>
   8:     0x55a23b65ba09 - <unknown>
   9:     0x55a23ada2303 - <unknown>
  10:     0x55a23ada23f3 - <unknown>
  11:     0x55a23b0adb2b - <unknown>
  12:     0x55a23b0c022d - <unknown>
  13:     0x55a23ae6629a - <unknown>
  14:     0x55a23afb64ad - <unknown>
  15:     0x55a23b0703ac - <unknown>
  16:     0x55a23add5c0b - <unknown>
  17:     0x55a23afa04e6 - <unknown>
  18:     0x55a23af012d3 - <unknown>
  19:     0x55a23b04e9c9 - <unknown>
  20:     0x55a23b64d64e - <unknown>
  21:     0x55a23afa23f2 - <unknown>
  22:     0x7f00297c3b80 - __libc_start_main
  23:     0x55a23ada25ae - <unknown>
  24:                0x0 - <unknown>flatpak info com.belmoussaoui.Authenticator                                                                                                                                                                                        
```

This was tested on Fedora 36 and Ubuntu 22.04 (in a virtual machine) running the KDE Plasma desktop (I assume this doesn't matter due to flatpak), both result in the same crash. Both systems and flatpak packages were updated prior to running the program (so the runtimes should be updated as well).

**Comment by Ferenc-** [comment]
If this it has any further value, then here is a bit more detailed backtrace:
````
ERROR authenticator::application: Failed to migrate your data Portal error Portal request was cancelled
[New Thread 0x7fffdabf8640 (LWP 100)]
thread 'main' panicked at 'Failed to start a location service: Portal(CancelledPortalRequest)', src/application.rs:326:18
stack backtrace:
[Thread 0x7fffdabf8640 (LWP 100) exited]
   0:     0x555555f0ad7d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x555555f0ad7d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555555f0ad7d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x555555f0ad7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x555555f2d7ec - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x555555f04ac1 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x555555f0c8a5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x555555f0c8a5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x555555f0c8a5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x555555f0c559 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x555555f0cdf2 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x555555f0ccd7 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:     0x555555f0b234 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x555555f0ca09 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:     0x555555653303 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:     0x5555556533f3 - core::result::unwrap_failed::hddd78f4658ac7d0f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
  16:     0x55555595eb2b - authenticator::application::Application::run::{{closure}}::h88bc9cd5d3da2563
  17:     0x55555597122d - std::thread::local::LocalKey<T>::with::he71773367a70a561
  18:     0x55555571729a - tokio::park::thread::CachedParkThread::block_on::h6d664f8aef45d48a
  19:     0x5555558674ad - tokio::runtime::thread_pool::ThreadPool::block_on::h7cf053086844739c
  20:     0x5555559213ac - tokio::runtime::Runtime::block_on::h366992514d1ec888
  21:     0x555555686c0b - authenticator::application::Application::run::h648f435d7f388723
  22:     0x5555558514e6 - authenticator::main::hd1d0071d55a2e74d
  23:     0x5555557b22d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hce212d0af29c5ad7
  24:     0x5555558ff9c9 - std::rt::lang_start::{{closure}}::h3ff532b653a748d2
  25:     0x555555efe64e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  26:     0x555555efe64e - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  27:     0x555555efe64e - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  28:     0x555555efe64e - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  29:     0x555555efe64e - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  30:     0x555555efe64e - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  31:     0x555555efe64e - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  32:     0x555555efe64e - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  33:     0x555555efe64e - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  34:     0x5555558533f2 - main
  35:     0x7ffff649eb80 - __libc_start_main
  36:     0x5555556535ae - _start
                               at /buildstream/freedesktop-sdk/bootstrap/glibc.bst/csu/../sysdeps/x86_64/start.S:120
  37:                0x0 - <unknown>
  ````
  @bilelmoussaoui let me know if I can provide more info.

**Comment by bilelmoussaoui** [comment]
The problem happens because you have nothing that provides a secret service https://specifications.freedesktop.org/secret-service/latest/, Authenticator tries first using the Secrets portal and falls back to using the host secret service and none of those are available on your system. 

I believe kwallet only implemented the secret service "protocol" recently, so you either have to update your system or install gnome-keyring for now until that lands to whatever distro you are using.

**Comment by Ferenc-** [comment]
@bilelmoussaoui  I believe that the `gnome-keyring-daemon` is supposed provide the secret service, isn't it?
It is up and running:
````
/usr/bin/gnome-keyring-daemon --foreground --components=pkcs11,secrets --control-directory=/run/user/1000/keyring
````

**Comment by Ferenc-** [comment]
https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/107

> So we concluded that it was searching for the wrong keyring. My default keyring is named Default_keyring.keyring. I created a symlink login.keyring that points to the other and then it worked

Yep, it was the wrong keyring for me too. After the symlink hack `Authenticator` starts. **But as it is written in the bug report, thousands of symlinks are created as a sideffect!**
Once those thousands of extra symlinks are cleaned up, everything seems to be normal.
